#!/bin/bash

###################################################################
# This script is planned to anlayze sequence info from PROSS runs #
# It should be executed from <results_dir>/PDBid/                 #
# Or from <results_dir>/uploaded_pdb_/ if a PDB file was uploaded #
###################################################################

###########################################
# Analysis of full MSA generated by PROSS #
###########################################

path_to_msa=$1
path_to_in=$2

echo -e "\nFOR EXPLANATION ABOUT THIS FILE READ THE RESULTS SECTION IN THE ABOUT PAGE"
echo -e "http://pross.weizmann.ac.il/help/Help/About.html#Q4"
echo -e "\nAnalysis of sequence variability"
echo -e "---------------------------------"

allseqs=$(grep ">" $path_to_msa | wc -l)
echo -e "Number of sequences in the MSA = $allseqs\n"

echo -e "Number of sequences sharing various levels of sequence identity to the query"
echo -e "----------------------------------------------------------------------------"

j=0
for i in {9..2}; do 
    j=$(($i*10))
    echo -e " > $j% = $(grep "Identities = $i" $path_to_msa | wc -l)";
done


###############################################
# Analysis of sub MSA filesgenerated by PROSS #
###############################################

echo -e "\nHow many sequences are in each sub MSA file"
echo -e "--------------------------------------------"

for i in $(ls -1 $path_to_in/sub_MSAs/ | grep -v PSSM | grep -v clw); do echo $i; grep ">" $path_to_in/sub_MSAs/$i | wc -l ; done

